// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecbmrrpssdmmoqygtknf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjYm1ycnBzc2RtbW9xeWd0a25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzQ1MTIsImV4cCI6MjA3MTA1MDUxMn0.A8CriuvTLVFE02ZW5ULZ4pSpNutER47X-sqr7K6lm-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});